/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C_1.h"
#include "I2C_1_PVT.h"
#include "TONE_Control_Reg.h"
#include "WaveDAC8_1.h"
#include "TONE_aliases.h"
#include "TONE.h"
#include "LED_aliases.h"
#include "LED.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "TC_IN_aliases.h"
#include "TC_IN.h"
#include "isr_TC_PULSE_END.h"
#include "clock_1.h"
#include "Counter_1.h"
#include "isr_TC_PULSE_DET.h"
#include "JJY_Control_Reg.h"
#include "counter_clock.h"
#include "timer_clock.h"
#include "Timer_1.h"
#include "timerISR_1.h"
#include "WaveDAC8_1_DacClk.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "core_cm3.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

